

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.prod
    command: gunicorn commerce.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/app/web/staticfiles
      - db_volume:/home/app/web
    ports:
      - "8000:8000"  # Map container's port 8000 to the host's port 8000
    env_file:
      - env/.env.prod
    # depends_on:
    #   - nginx

  nginx:
    image: nginx:latest
    build: ./nginx
    ports:
      - 80:80
    volumes:
      - static_volume:/home/app/web/staticfiles
    depends_on:
      - web

volumes:
  static_volume:
  db_volume:
