# Generated by Django 4.1.1 on 2022-12-13 09:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_watchlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='bid_price',
            field=models.IntegerField(default=0, max_length=5),
        ),
        migrations.AddField(
            model_name='bid',
            name='bidding_user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='bidding_user_related', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='watchlist',
            name='listing',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='listing_watchlist', to='auctions.listing'),
        ),
        migrations.AlterField(
            model_name='watchlist',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='listing_owner_watchlist', to=settings.AUTH_USER_MODEL),
        ),
    ]
