# Generated by Django 4.1.1 on 2022-12-13 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_bid_bid_price_bid_bidding_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='bidding_listing',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='bidding_listing_related', to='auctions.listing'),
        ),
    ]
