# Generated by Django 4.1.1 on 2022-12-13 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_bid_bidding_listing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='bidding_listing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bidding_listing_related', to='auctions.listing'),
        ),
    ]
