# Generated by Django 4.1.1 on 2022-12-14 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_listing_comment_alter_comment_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='comment_owner',
            field=models.CharField(default='', max_length=50, null=True),
        ),
    ]
